name: Check Chains

on:
  push:
    paths:
      - 'nftpy/EVM/chains.py'
  pull_request:
    paths:
      - 'nftpy/EVM/chains.py'

jobs:
  check-chains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip3 install web3
        pip3 install requests
        pip3 install nftpy

    - name: Run RPC URL check
      run: |
        source venv/bin/activate
        python tests/check_rpc_url.py
